apiVersion: v1
kind: Pod
metadata:
  name: alpine-syslog
  namespace: confluent
spec:
  containers:
  - image: alpine-syslog:3.18.3
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    imagePullPolicy: IfNotPresent
    name: alpine-syslog
  restartPolicy: Always