auth:
  rootPassword: change-me
  database: mariadb
  username: mariadb
  password: change-me

primary:
  service:
    type: NodePort
    nodePorts:
      mysql: 30922
  extraVolumes:
    - name: mariadb
      secret:
        secretName: mariadb-pkcs12
  extraVolumeMounts:
    - mountPath: /mnt/sslcerts
      name: mariadb
  configuration: |-
    [mysqld]
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mariadb
    plugin_dir=/opt/bitnami/mariadb/plugin
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    tmpdir=/opt/bitnami/mariadb/tmp
    max_allowed_packet=16M
    bind-address=*
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
    log-error=/opt/bitnami/mariadb/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci
    slow_query_log=0
    slow_query_log_file=/opt/bitnami/mariadb/logs/mysqld.log
    long_query_time=10.0
    require_secure_transport = OFF
    ssl-ca=/mnt/sslcerts/ca.pem
    ssl-cert=/mnt/sslcerts/mariadb.pem
    ssl-key=/mnt/sslcerts/mariadb-key.pem

    [client]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/bitnami/mariadb/plugin

    [manager]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
      
image:
  debug: true
