image:
  repository: osixia/phpldapadmin-vf
  tag: 0.9.0

env:
  PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'ldap://ldap.confluent.svc.cluster.local:389': [{'server': [{'tls': False}]},{'login': [{'bind_id': 'cn=admin,dc=test,dc=com'}]}]}, {'ldaps://ldap.confluent.svc.cluster.local:636': [{'server': [{'tls': False}]},{'login': [{'bind_id': 'cn=admin,dc=test,dc=com'}]}]}]"
  PHPLDAPADMIN_HTTPS: "true"
  PHPLDAPADMIN_HTTPS_CRT_FILENAME: "phpldapadmin.pem"
  PHPLDAPADMIN_HTTPS_KEY_FILENAME: "phpldapadmin-key.pem"
  PHPLDAPADMIN_HTTPS_CA_CRT_FILENAME: "ca.pem"
  PHPLDAPADMIN_LDAP_CLIENT_TLS: "true"
  PHPLDAPADMIN_LDAP_CLIENT_TLS_REQCERT: "demand"  
  PHPLDAPADMIN_LDAP_CLIENT_TLS_CA_CRT_FILENAME: "ca.pem"
  PHPLDAPADMIN_LDAP_CLIENT_TLS_CRT_FILENAME: "server.pem"
  PHPLDAPADMIN_LDAP_CLIENT_TLS_KEY_FILENAME: "server-key.pem"
  CONTAINER_SERVICE_DIR: "/container/service"
  
service:
  type: NodePort
  # The nodePort is defined through a 'kubectl patch' command in the install script because this Helm chart does not support setting the nodePort in the values file.
  # Please find below the exact command used in the install script (scripts/install.sh)."
  # kubectl patch service phpldapadmin -p '{"spec": {"ports": [{"name": "https","port": 443,"nodePort": 30902}]}}'

readinessProbe:
    httpGet:
      path: /
      port: 443
      scheme: HTTPS

livenessProbe:
    httpGet:
      path: /
      port: 443
      scheme: HTTPS
