image:
  repository: osixia/phpldapadmin-vf
  tag: 0.9.0

env:
  PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'ldap://ldap.confluent.svc.cluster.local:389': [{'server': [{'tls': False}]},{'login': [{'bind_id': 'cn=admin,dc=test,dc=com'}]}]}, {'ldaps://ldap.confluent.svc.cluster.local:636': [{'server': [{'tls': True}]},{'login': [{'bind_id': 'cn=admin,dc=test,dc=com'}]}]}]"
  PHPLDAPADMIN_HTTPS: "true"
  PHPLDAPADMIN_HTTPS_CRT_FILENAME: "server.pem"
  PHPLDAPADMIN_HTTPS_KEY_FILENAME: "server-key.pem"
  PHPLDAPADMIN_HTTPS_CA_CRT_FILENAME: "ca.pem"

service:
  type: NodePort

readinessProbe:
    httpGet:
      path: /
      port: 443
      scheme: HTTPS

livenessProbe:
    httpGet:
      path: /
      port: 443
      scheme: HTTPS
