global:
  postgresql:
    auth:
      postgresPassword: "change-me"

primary:
  service:
    type: NodePort
    nodePorts:
      postgresql: 30920

tls:
  enabled: true
  certificatesSecret: postgres-pkcs12
  certFilename: cert.pem
  certKeyFilename: cert.key
  certCAFilename: ca.pem
