global:
  postgresql:
    auth:
      postgresPassword: "change-me"

primary:
  service:
    type: NodePort
    nodePorts:
      postgresql: 30902
  
  pgHbaConfiguration: |-
    hostssl     all             all             0.0.0.0/0               cert
    hostssl     all             all             ::/0                    cert

tls:
  enabled: true
  certificatesSecret: postgres-pkcs12
  certFilename: cert.pem
  certKeyFilename: cert.key
  certCAFilename: ca.pem
