replicaCount: 1

image:
  repository: obsidiandynamics/kafdrop
  tag: latest
  pullPolicy: Always

kafka:
  brokerConnect: kafka.confluent.svc.cluster.local:9092
  properties: ""
  truststore: ""
  keystore: ""
  propertiesFile: "/mnt/sslcerts/kafka.properties"
  truststoreFile: "/mnt/sslcerts/truststore.p12"
  keystoreFile: "/mnt/sslcerts/keystore.p12"

host:

jvm:
  opts: ""
jmx:
  port: 8686

nameOverride: ""
fullnameOverride: ""

cmdArgs: ""

global:
  kubeVersion: ~

server:
  port: 9000
  servlet:
    contextPath: /

service:
  annotations: {}
  type: NodePort
  port: 9000
  nodePort: 30902

ingress:
  enabled: false
  annotations: {}
  apiVersion: ~
  #ingressClassName: ~
  path: /
  #pathType: ~
  hosts: []
  tls: []

resources:
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  requests:
    cpu: 1m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

hostAliases: []

mountProtoDesc: 
  enabled: false
  hostPath:

mountCertificates:
  enabled: true
  name: kafdrop-pkcs12
  secretName: kafdrop-pkcs12
  mountPath: /mnt/sslcerts
  defaultMode: 420
